In [44]:
#Import necessary libraries
import os
import pandas as pd
import json

In [45]:
#Set the working directory 
#os.chdir("/Users/Abdul/Desktop/MMA/Enterprise Data Science/Revenue-Radar/Data")

In [46]:
#Import dataset(s)
train_revenue = pd.read_csv("Data/train.csv")
test_revenue = pd.read_csv("Data/test.csv")

/var/folders/9z/gkk8fkkj0pz746hrzcw69dq40000gn/T/ipykernel_5023/2625106073.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  train_revenue = pd.read_csv("Data/train.csv")
/var/folders/9z/gkk8fkkj0pz746hrzcw69dq40000gn/T/ipykernel_5023/2625106073.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  test_revenue = pd.read_csv("Data/test.csv")

In [47]:
dict_columns = ['geoNetwork', 'device', 'totals', 'trafficSource']

# For each such column, convert the string representation of dictionary to actual dictionary
# then normalize and concatenate with the original DataFrame
for column in dict_columns:
    # Convert the stringified dictionary to actual dictionary
    train_revenue[column] = train_revenue[column].apply(json.loads)
    
    # Flatten the dictionary and convert to a DataFrame
    column_df = pd.json_normalize(train_revenue[column])
    
    # Concatenate the new DataFrame to the original DataFrame
    train_revenue = pd.concat([train_revenue, column_df], axis=1)

    # Drop the original column that contained the stringified dictionary
    train_revenue.drop(column, axis=1, inplace=True)

### Seprating the code from above to make the waiting time shorter and to have some progress

In [ ]:
for column in dict_columns:
    # Convert the stringified dictionary to actual dictionary
    test_revenue[column] = test_revenue[column].apply(json.loads)
    
    # Flatten the dictionary and convert to a DataFrame
    column_df = pd.json_normalize(test_revenue[column])
    
    # Concatenate the new DataFrame to the original DataFrame
    test_revenue = pd.concat([test_revenue, column_df], axis=1)

    # Drop the original column that contained the stringified dictionary
    test_revenue.drop(column, axis=1, inplace=True)

### THE ABOVE TAKE TOOOO LONG to Run, let's save the data into new dataframe, avoid running it everytime

In [ ]:
#  saving the data to new dataframes to make sure we don't have to run the above code again, it takes me 10 minutes to run
train_data = train_revenue
test_data = test_revenue

In [42]:
#Viewing first 5 rows of the training dataset
train_data.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,continent,subContinent,...,adwordsClickInfo.criteriaParameters,isTrueDirect,referralPath,adwordsClickInfo.page,adwordsClickInfo.slot,adwordsClickInfo.gclId,adwordsClickInfo.adNetworkType,adwordsClickInfo.isVideoAd,adContent,campaignCode
0,Organic Search,NaT,1131660440785968503,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Asia,Western Asia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,NaT,377306020877927890,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Oceania,Australasia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,NaT,3895546263509774583,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Europe,Southern Europe,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,NaT,4763447161404445595,4763447161404445595_1472881213,Not Socially Engaged,1472881213,1,1472881213,Asia,Southeast Asia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,NaT,27294437909732085,27294437909732085_1472822600,Not Socially Engaged,1472822600,2,1472822600,Europe,Northern Europe,...,not available in demo dataset,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# help me make date to YYYYMMDD
train_data['date'] = pd.to_datetime(train_data['date'], format='%Y%m%d')
train_data.head()

#check are there any missing values in the training dataset

#check are there any date gaps in the training dataset

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,continent,subContinent,...,adwordsClickInfo.criteriaParameters,isTrueDirect,referralPath,adwordsClickInfo.page,adwordsClickInfo.slot,adwordsClickInfo.gclId,adwordsClickInfo.adNetworkType,adwordsClickInfo.isVideoAd,adContent,campaignCode
0,Organic Search,NaT,1131660440785968503,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Asia,Western Asia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,NaT,377306020877927890,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Oceania,Australasia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,NaT,3895546263509774583,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Europe,Southern Europe,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,NaT,4763447161404445595,4763447161404445595_1472881213,Not Socially Engaged,1472881213,1,1472881213,Asia,Southeast Asia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,NaT,27294437909732085,27294437909732085_1472822600,Not Socially Engaged,1472822600,2,1472822600,Europe,Northern Europe,...,not available in demo dataset,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Viewing first 5 rows of the testing dataset
test_revenue.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,continent,subContinent,...,keyword,isTrueDirect,adwordsClickInfo.criteriaParameters,adwordsClickInfo.page,adwordsClickInfo.slot,adwordsClickInfo.gclId,adwordsClickInfo.adNetworkType,adwordsClickInfo.isVideoAd,referralPath,adContent
0,Organic Search,20171016,6167871330617112363,6167871330617112363_1508151024,Not Socially Engaged,1508151024,2,1508151024,Asia,Southeast Asia,...,(not provided),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,20171016,0643697640977915618,0643697640977915618_1508175522,Not Socially Engaged,1508175522,1,1508175522,Europe,Southern Europe,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20171016,6059383810968229466,6059383810968229466_1508143220,Not Socially Engaged,1508143220,1,1508143220,Europe,Western Europe,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,20171016,2376720078563423631,2376720078563423631_1508193530,Not Socially Engaged,1508193530,1,1508193530,Americas,Northern America,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20171016,2314544520795440038,2314544520795440038_1508217442,Not Socially Engaged,1508217442,1,1508217442,Americas,Northern America,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#importing the training set
df_train=pd.read_csv("/Users/Abdul/Desktop/MMA/Enterprise Data Science/Revenue-Radar/Data/train_dejsonified.csv")

# #Importing the test set
df_test=pd.read_csv("/Users/Abdul/Desktop/MMA/Enterprise Data Science/Revenue-Radar/Data/test_dejsonified.csv")

/var/folders/rj/g3r71fsx2vnbbbjb9v368gr00000gp/T/ipykernel_8822/1251306950.py:2: DtypeWarning: Columns (2,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train=pd.read_csv("/Users/Abdul/Desktop/MMA/Enterprise Data Science/Revenue-Radar/Data/train_dejsonified.csv")
/var/folders/rj/g3r71fsx2vnbbbjb9v368gr00000gp/T/ipykernel_8822/1251306950.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_test=pd.read_csv("/Users/Abdul/Desktop/MMA/Enterprise Data Science/Revenue-Radar/Data/test_dejsonified.csv")

In [ ]:
print('The dimensions of the training dataset are:', df_train.shape)
print('The dimensions of the testing dataset are:', df_test.shape)

The dimensions of the training dataset are: (903653, 55)
The dimensions of the testing dataset are: (804684, 53)

In [ ]:
# Printing all the column names for exploration and understanding the dataset
df_train.columns.to_list()

['channelGrouping',
 'date',
 'fullVisitorId',
 'sessionId',
 'socialEngagementType',
 'visitId',
 'visitNumber',
 'visitStartTime',
 'continent',
 'subContinent',
 'country',
 'region',
 'metro',
 'city',
 'cityId',
 'networkDomain',
 'latitude',
 'longitude',
 'networkLocation',
 'browser',
 'browserVersion',
 'browserSize',
 'operatingSystem',
 'operatingSystemVersion',
 'isMobile',
 'mobileDeviceBranding',
 'mobileDeviceModel',
 'mobileInputSelector',
 'mobileDeviceInfo',
 'mobileDeviceMarketingName',
 'flashVersion',
 'language',
 'screenColors',
 'screenResolution',
 'deviceCategory',
 'visits',
 'hits',
 'pageviews',
 'bounces',
 'newVisits',
 'transactionRevenue',
 'campaign',
 'source',
 'medium',
 'keyword',
 'adwordsClickInfo.criteriaParameters',
 'isTrueDirect',
 'referralPath',
 'adwordsClickInfo.page',
 'adwordsClickInfo.slot',
 'adwordsClickInfo.gclId',
 'adwordsClickInfo.adNetworkType',
 'adwordsClickInfo.isVideoAd',
 'adContent',
 'campaignCode']

In [ ]:
# printing all the column names for exploration and understanding the dataset. Also, there are less columns in the test dataset. Upon inspection, it is found that the test dataset does not have the 'revenue' column which is the target variable that we are trying to predict.
df_test.columns.to_list()

['channelGrouping',
 'date',
 'fullVisitorId',
 'sessionId',
 'socialEngagementType',
 'visitId',
 'visitNumber',
 'visitStartTime',
 'continent',
 'subContinent',
 'country',
 'region',
 'metro',
 'city',
 'cityId',
 'networkDomain',
 'latitude',
 'longitude',
 'networkLocation',
 'browser',
 'browserVersion',
 'browserSize',
 'operatingSystem',
 'operatingSystemVersion',
 'isMobile',
 'mobileDeviceBranding',
 'mobileDeviceModel',
 'mobileInputSelector',
 'mobileDeviceInfo',
 'mobileDeviceMarketingName',
 'flashVersion',
 'language',
 'screenColors',
 'screenResolution',
 'deviceCategory',
 'visits',
 'hits',
 'pageviews',
 'newVisits',
 'bounces',
 'campaign',
 'source',
 'medium',
 'keyword',
 'isTrueDirect',
 'adwordsClickInfo.criteriaParameters',
 'adwordsClickInfo.page',
 'adwordsClickInfo.slot',
 'adwordsClickInfo.gclId',
 'adwordsClickInfo.adNetworkType',
 'adwordsClickInfo.isVideoAd',
 'referralPath',
 'adContent']

In [ ]:
# Inspecting proportion of missing values in the transactioRevenue column (This info is useful for the classification model)
print('The proportion of missing values in the transactionRevenue column is:',df_train['transactionRevenue'].isnull().sum()/len(df_train))
# Inspecting the number of non-null values in the transactioRevenue column ( The subset is useful for the regression model)
print('The number of non-null values in the transactionRevenue column is:',df_train['transactionRevenue'].notnull().sum())

The proportion of missing values in the transactionRevenue column is: 0.9872572768529513
The number of non-null values in the transactionRevenue column is: 11515

In [ ]:
def subset_data(df):
    reg_df=df[df['transactionRevenue'].notnull()]

    return reg_df

In [ ]:
reg_df=subset_data(df_train)

In [ ]:
reg_df.shape

(11515, 55)

In [6]:
# Replace my path with yours
reg_df.to_csv('/Users/macbookpro/Desktop/lxc/git/M/Data/train.csv', index=False)

NameError: name 'reg_df' is not defined